#!/bin/bash
git add . && git commit -m "edit" && \
git push origin syn-github && \
git rm -r . --cache

sh ./switch 

git add . && git commit -m "edit" && \
git push origin syn-svn && \
git rm -r . --cache
